from .auth import UserCreate, UserLogin, Token, UserResponse
from .admission import (
    StudentDetailsSchema,
    ParentDetailsSchema,
    AddressSchema,
    ApplicationCreate,
    ApplicationUpdate,
    ApplicationStatusUpdate,
    ApplicationResponse,
    ApplicationListResponse,
    DocumentUploadResponse,
    DocumentVerification,
    TestSchedule,
    TestResult,
    InterviewSchedule,
    InterviewFeedback,
    ApplicationFilter
)

__all__ = [
    "UserCreate",
    "UserLogin",
    "Token",
    "UserResponse",
    "StudentDetailsSchema",
    "ParentDetailsSchema",
    "AddressSchema",
    "ApplicationCreate",
    "ApplicationUpdate",
    "ApplicationStatusUpdate",
    "ApplicationResponse",
    "ApplicationListResponse",
    "DocumentUploadResponse",
    "DocumentVerification",
    "TestSchedule",
    "TestResult",
    "InterviewSchedule",
    "InterviewFeedback",
    "ApplicationFilter",
]
