"""Add fee management tables

Revision ID: 36c061152bdb
Revises: 
Create Date: 2025-10-14 13:07:19.012725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '36c061152bdb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('is_refundable', sa.Boolean(), nullable=True),
    sa.Column('frequency', sa.Enum('ONE_TIME', 'MONTHLY', 'QUARTERLY', 'HALF_YEARLY', 'ANNUAL', 'CUSTOM', name='feefrequency'), nullable=True),
    sa.Column('is_taxable', sa.Boolean(), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_types_code'), 'fee_types', ['code'], unique=True)
    op.create_index(op.f('ix_fee_types_id'), 'fee_types', ['id'], unique=False)
    op.create_index(op.f('ix_fee_types_is_active'), 'fee_types', ['is_active'], unique=False)
    op.create_index(op.f('ix_fee_types_type_name'), 'fee_types', ['type_name'], unique=True)
    op.create_table('fee_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('fee_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_day_of_month', sa.Integer(), nullable=True),
    sa.Column('late_fee_applicable', sa.Boolean(), nullable=True),
    sa.Column('late_fee_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('late_fee_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('grace_period_days', sa.Integer(), nullable=True),
    sa.Column('sibling_discount_applicable', sa.Boolean(), nullable=True),
    sa.Column('early_payment_discount_applicable', sa.Boolean(), nullable=True),
    sa.Column('early_payment_discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('early_payment_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fee_type_id'], ['fee_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_structures_academic_year_id'), 'fee_structures', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_fee_structures_class_id'), 'fee_structures', ['class_id'], unique=False)
    op.create_index(op.f('ix_fee_structures_fee_type_id'), 'fee_structures', ['fee_type_id'], unique=False)
    op.create_index(op.f('ix_fee_structures_id'), 'fee_structures', ['id'], unique=False)
    op.create_index(op.f('ix_fee_structures_is_active'), 'fee_structures', ['is_active'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('late_fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('is_overdue', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'VIEWED', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED', 'REFUNDED', name='invoicestatus'), nullable=True),
    sa.Column('sent_via_email', sa.Boolean(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_via_sms', sa.Boolean(), nullable=True),
    sa.Column('sms_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fully_paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('place_of_supply', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_created_at'), 'invoices', ['created_at'], unique=False)
    op.create_index(op.f('ix_invoices_due_date'), 'invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_is_overdue'), 'invoices', ['is_overdue'], unique=False)
    op.create_index(op.f('ix_invoices_parent_id'), 'invoices', ['parent_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_student_id'), 'invoices', ['student_id'], unique=False)
    op.create_table('student_fee_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('total_fees_assigned', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_invoiced', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_outstanding', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_refunded', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_waived', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_discounts', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('overdue_0_30_days', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('overdue_30_60_days', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('overdue_60_90_days', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('overdue_90_plus_days', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_late_fees', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('late_fees_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('late_fees_outstanding', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_payment_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_count', sa.Integer(), nullable=True),
    sa.Column('invoice_count', sa.Integer(), nullable=True),
    sa.Column('pending_invoice_count', sa.Integer(), nullable=True),
    sa.Column('paid_invoice_count', sa.Integer(), nullable=True),
    sa.Column('overdue_invoice_count', sa.Integer(), nullable=True),
    sa.Column('has_outstanding', sa.Boolean(), nullable=True),
    sa.Column('has_overdue', sa.Boolean(), nullable=True),
    sa.Column('is_defaulter', sa.Boolean(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_fee_ledger_has_outstanding'), 'student_fee_ledger', ['has_outstanding'], unique=False)
    op.create_index(op.f('ix_student_fee_ledger_has_overdue'), 'student_fee_ledger', ['has_overdue'], unique=False)
    op.create_index(op.f('ix_student_fee_ledger_id'), 'student_fee_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_student_fee_ledger_is_defaulter'), 'student_fee_ledger', ['is_defaulter'], unique=False)
    op.create_index(op.f('ix_student_fee_ledger_last_updated_at'), 'student_fee_ledger', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_student_fee_ledger_student_id'), 'student_fee_ledger', ['student_id'], unique=True)
    op.create_index(op.f('ix_student_fee_ledger_total_outstanding'), 'student_fee_ledger', ['total_outstanding'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_number', sa.String(length=30), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.Enum('UPI', 'CREDIT_CARD', 'DEBIT_CARD', 'NET_BANKING', 'WALLET', 'CASH', 'CHEQUE', 'DEMAND_DRAFT', 'BANK_TRANSFER', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'CANCELLED', 'REFUND_INITIATED', 'REFUNDED', 'DISPUTED', name='paymentstatus'), nullable=True),
    sa.Column('gateway_name', sa.String(length=50), nullable=True),
    sa.Column('gateway_order_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_signature', sa.String(length=500), nullable=True),
    sa.Column('gateway_response', sa.JSON(), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('bank_reference', sa.String(length=100), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('cheque_number', sa.String(length=20), nullable=True),
    sa.Column('cheque_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('branch_name', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconciled_by', sa.Integer(), nullable=True),
    sa.Column('is_refunded', sa.Boolean(), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('refund_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_initiated_by', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('failure_code', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reconciled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['refund_initiated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_gateway_order_id'), 'payments', ['gateway_order_id'], unique=False)
    op.create_index(op.f('ix_payments_gateway_payment_id'), 'payments', ['gateway_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_is_reconciled'), 'payments', ['is_reconciled'], unique=False)
    op.create_index(op.f('ix_payments_parent_id'), 'payments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_payment_method'), 'payments', ['payment_method'], unique=False)
    op.create_index(op.f('ix_payments_payment_number'), 'payments', ['payment_number'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_student_id'), 'payments', ['student_id'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=False)
    op.create_table('student_fee_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('fee_structure_id', sa.Integer(), nullable=False),
    sa.Column('custom_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_reason', sa.String(length=200), nullable=True),
    sa.Column('custom_due_date', sa.Date(), nullable=True),
    sa.Column('is_waived', sa.Boolean(), nullable=True),
    sa.Column('waiver_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('waiver_reason', sa.Text(), nullable=True),
    sa.Column('waived_by', sa.Integer(), nullable=True),
    sa.Column('waived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waived_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_fee_assignments_fee_structure_id'), 'student_fee_assignments', ['fee_structure_id'], unique=False)
    op.create_index(op.f('ix_student_fee_assignments_id'), 'student_fee_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_student_fee_assignments_is_active'), 'student_fee_assignments', ['is_active'], unique=False)
    op.create_index(op.f('ix_student_fee_assignments_student_id'), 'student_fee_assignments', ['student_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('fee_type_id', sa.Integer(), nullable=False),
    sa.Column('fee_assignment_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['fee_assignment_id'], ['student_fee_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fee_type_id'], ['fee_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('payment_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=30), nullable=False),
    sa.Column('receipt_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('file_size_kb', sa.Integer(), nullable=True),
    sa.Column('sent_via_email', sa.Boolean(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_to', sa.String(length=200), nullable=True),
    sa.Column('sent_via_sms', sa.Boolean(), nullable=True),
    sa.Column('sms_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sms_to', sa.String(length=20), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('is_regenerated', sa.Boolean(), nullable=True),
    sa.Column('regenerated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('regenerated_by', sa.Integer(), nullable=True),
    sa.Column('regeneration_reason', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regenerated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_receipts_id'), 'payment_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_payment_receipts_payment_id'), 'payment_receipts', ['payment_id'], unique=True)
    op.create_index(op.f('ix_payment_receipts_receipt_date'), 'payment_receipts', ['receipt_date'], unique=False)
    op.create_index(op.f('ix_payment_receipts_receipt_number'), 'payment_receipts', ['receipt_number'], unique=True)
    op.drop_index(op.f('ix_form_fields_master_field_code'), table_name='form_fields_master')
    op.drop_index(op.f('ix_form_fields_master_id'), table_name='form_fields_master')
    op.drop_table('form_fields_master')
    op.drop_index(op.f('ix_form_templates_id'), table_name='form_templates')
    op.drop_table('form_templates')
    op.drop_index(op.f('ix_admission_workflow_steps_id'), table_name='admission_workflow_steps')
    op.drop_index(op.f('ix_admission_workflow_steps_step_order'), table_name='admission_workflow_steps')
    op.drop_table('admission_workflow_steps')
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_school_code'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_application_field_responses_application_id'), table_name='application_field_responses')
    op.drop_index(op.f('ix_application_field_responses_id'), table_name='application_field_responses')
    op.drop_index(op.f('ix_application_field_responses_school_id'), table_name='application_field_responses')
    op.drop_table('application_field_responses')
    op.drop_index(op.f('ix_form_template_fields_id'), table_name='form_template_fields')
    op.drop_table('form_template_fields')
    op.drop_index(op.f('ix_school_form_configurations_id'), table_name='school_form_configurations')
    op.drop_index(op.f('ix_school_form_configurations_school_id'), table_name='school_form_configurations')
    op.drop_table('school_form_configurations')
    op.drop_index(op.f('ix_application_workflow_progress_application_id'), table_name='application_workflow_progress')
    op.drop_index(op.f('ix_application_workflow_progress_id'), table_name='application_workflow_progress')
    op.drop_index(op.f('ix_application_workflow_progress_workflow_step_id'), table_name='application_workflow_progress')
    op.drop_table('application_workflow_progress')
    op.drop_index(op.f('ix_form_configurations_id'), table_name='form_configurations')
    op.drop_index(op.f('ix_form_configurations_school_id'), table_name='form_configurations')
    op.drop_table('form_configurations')
    op.drop_index(op.f('ix_application_field_reviews_application_id'), table_name='application_field_reviews')
    op.drop_index(op.f('ix_application_field_reviews_id'), table_name='application_field_reviews')
    op.drop_table('application_field_reviews')
    op.drop_index(op.f('ix_application_reviews_application_id'), table_name='application_reviews')
    op.drop_index(op.f('ix_application_reviews_id'), table_name='application_reviews')
    op.drop_table('application_reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('application_id', sa.INTEGER(), nullable=False),
    sa.Column('review_status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('overall_remarks', sa.TEXT(), nullable=True),
    sa.Column('version_number', sa.INTEGER(), nullable=False),
    sa.Column('reviewed_by', sa.INTEGER(), nullable=False),
    sa.Column('reviewed_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['admission_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_reviews_id'), 'application_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_application_reviews_application_id'), 'application_reviews', ['application_id'], unique=False)
    op.create_table('application_field_reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('application_id', sa.INTEGER(), nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('field_label', sa.VARCHAR(length=200), nullable=True),
    sa.Column('field_value', sa.TEXT(), nullable=True),
    sa.Column('needs_correction', sa.BOOLEAN(), nullable=False),
    sa.Column('admin_comment', sa.TEXT(), nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), nullable=False),
    sa.Column('reviewed_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['admission_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_field_reviews_id'), 'application_field_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_application_field_reviews_application_id'), 'application_field_reviews', ['application_id'], unique=False)
    op.create_table('form_configurations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('school_id', sa.INTEGER(), nullable=False),
    sa.Column('form_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('form_description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_configurations_school_id'), 'form_configurations', ['school_id'], unique=False)
    op.create_index(op.f('ix_form_configurations_id'), 'form_configurations', ['id'], unique=False)
    op.create_table('application_workflow_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('application_id', sa.INTEGER(), nullable=True),
    sa.Column('workflow_step_id', sa.INTEGER(), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('is_current', sa.BOOLEAN(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_by', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['admission_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_step_id'], ['admission_workflow_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_workflow_progress_workflow_step_id'), 'application_workflow_progress', ['workflow_step_id'], unique=False)
    op.create_index(op.f('ix_application_workflow_progress_id'), 'application_workflow_progress', ['id'], unique=False)
    op.create_index(op.f('ix_application_workflow_progress_application_id'), 'application_workflow_progress', ['application_id'], unique=False)
    op.create_table('school_form_configurations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('school_id', sa.INTEGER(), nullable=False),
    sa.Column('field_id', sa.INTEGER(), nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('is_required', sa.BOOLEAN(), nullable=True),
    sa.Column('step_number', sa.INTEGER(), nullable=False),
    sa.Column('display_order', sa.INTEGER(), nullable=False),
    sa.Column('conditional_logic', sqlite.JSON(), nullable=True),
    sa.Column('custom_label', sa.VARCHAR(length=200), nullable=True),
    sa.Column('custom_help_text', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('form_config_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields_master.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_form_configurations_school_id'), 'school_form_configurations', ['school_id'], unique=False)
    op.create_index(op.f('ix_school_form_configurations_id'), 'school_form_configurations', ['id'], unique=False)
    op.create_table('form_template_fields',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('template_id', sa.INTEGER(), nullable=False),
    sa.Column('field_id', sa.INTEGER(), nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('is_required', sa.BOOLEAN(), nullable=True),
    sa.Column('step_number', sa.INTEGER(), nullable=False),
    sa.Column('display_order', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields_master.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['form_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_template_fields_id'), 'form_template_fields', ['id'], unique=False)
    op.create_table('application_field_responses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('school_id', sa.INTEGER(), nullable=False),
    sa.Column('application_id', sa.INTEGER(), nullable=False),
    sa.Column('field_id', sa.INTEGER(), nullable=False),
    sa.Column('response_value', sa.TEXT(), nullable=True),
    sa.Column('response_json', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['admission_applications.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields_master.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_field_responses_school_id'), 'application_field_responses', ['school_id'], unique=False)
    op.create_index(op.f('ix_application_field_responses_id'), 'application_field_responses', ['id'], unique=False)
    op.create_index(op.f('ix_application_field_responses_application_id'), 'application_field_responses', ['application_id'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('school_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('school_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('subdomain', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('logo_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain')
    )
    op.create_index(op.f('ix_schools_school_code'), 'schools', ['school_code'], unique=1)
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=False)
    op.create_table('admission_workflow_steps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('step_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('step_description', sa.TEXT(), nullable=True),
    sa.Column('step_order', sa.INTEGER(), nullable=False),
    sa.Column('is_required', sa.BOOLEAN(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admission_workflow_steps_step_order'), 'admission_workflow_steps', ['step_order'], unique=False)
    op.create_index(op.f('ix_admission_workflow_steps_id'), 'admission_workflow_steps', ['id'], unique=False)
    op.create_table('form_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('template_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('template_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_code'),
    sa.UniqueConstraint('template_name')
    )
    op.create_index(op.f('ix_form_templates_id'), 'form_templates', ['id'], unique=False)
    op.create_table('form_fields_master',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('field_code', sa.VARCHAR(length=100), nullable=False),
    sa.Column('field_label', sa.VARCHAR(length=200), nullable=False),
    sa.Column('field_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('default_step', sa.INTEGER(), nullable=True),
    sa.Column('is_required_by_default', sa.BOOLEAN(), nullable=True),
    sa.Column('validation_rules', sqlite.JSON(), nullable=True),
    sa.Column('help_text', sa.TEXT(), nullable=True),
    sa.Column('placeholder', sa.VARCHAR(length=200), nullable=True),
    sa.Column('options', sqlite.JSON(), nullable=True),
    sa.Column('file_config', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_fields_master_id'), 'form_fields_master', ['id'], unique=False)
    op.create_index(op.f('ix_form_fields_master_field_code'), 'form_fields_master', ['field_code'], unique=1)
    op.drop_index(op.f('ix_payment_receipts_receipt_number'), table_name='payment_receipts')
    op.drop_index(op.f('ix_payment_receipts_receipt_date'), table_name='payment_receipts')
    op.drop_index(op.f('ix_payment_receipts_payment_id'), table_name='payment_receipts')
    op.drop_index(op.f('ix_payment_receipts_id'), table_name='payment_receipts')
    op.drop_table('payment_receipts')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_student_fee_assignments_student_id'), table_name='student_fee_assignments')
    op.drop_index(op.f('ix_student_fee_assignments_is_active'), table_name='student_fee_assignments')
    op.drop_index(op.f('ix_student_fee_assignments_id'), table_name='student_fee_assignments')
    op.drop_index(op.f('ix_student_fee_assignments_fee_structure_id'), table_name='student_fee_assignments')
    op.drop_table('student_fee_assignments')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_student_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_number'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_method'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_parent_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_is_reconciled'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_gateway_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_gateway_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_student_fee_ledger_total_outstanding'), table_name='student_fee_ledger')
    op.drop_index(op.f('ix_student_fee_ledger_student_id'), table_name='student_fee_ledger')
    op.drop_index(op.f('ix_student_fee_ledger_last_updated_at'), table_name='student_fee_ledger')
    op.drop_index(op.f('ix_student_fee_ledger_is_defaulter'), table_name='student_fee_ledger')
    op.drop_index(op.f('ix_student_fee_ledger_id'), table_name='student_fee_ledger')
    op.drop_index(op.f('ix_student_fee_ledger_has_overdue'), table_name='student_fee_ledger')
    op.drop_index(op.f('ix_student_fee_ledger_has_outstanding'), table_name='student_fee_ledger')
    op.drop_table('student_fee_ledger')
    op.drop_index(op.f('ix_invoices_student_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_parent_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_is_overdue'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_due_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_at'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_fee_structures_is_active'), table_name='fee_structures')
    op.drop_index(op.f('ix_fee_structures_id'), table_name='fee_structures')
    op.drop_index(op.f('ix_fee_structures_fee_type_id'), table_name='fee_structures')
    op.drop_index(op.f('ix_fee_structures_class_id'), table_name='fee_structures')
    op.drop_index(op.f('ix_fee_structures_academic_year_id'), table_name='fee_structures')
    op.drop_table('fee_structures')
    op.drop_index(op.f('ix_fee_types_type_name'), table_name='fee_types')
    op.drop_index(op.f('ix_fee_types_is_active'), table_name='fee_types')
    op.drop_index(op.f('ix_fee_types_id'), table_name='fee_types')
    op.drop_index(op.f('ix_fee_types_code'), table_name='fee_types')
    op.drop_table('fee_types')
    # ### end Alembic commands ###
