"""Add communication tables for messaging system

Revision ID: e51de1cd2327
Revises: 36c061152bdb
Create Date: 2025-10-15 20:39:02.744068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'e51de1cd2327'
down_revision: Union[str, Sequence[str], None] = '36c061152bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app_notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('daily_digest_enabled', sa.Boolean(), nullable=True),
    sa.Column('instant_notifications', sa.Boolean(), nullable=True),
    sa.Column('dnd_start_time', sa.String(length=5), nullable=True),
    sa.Column('dnd_end_time', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_preferences_id'), 'communication_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_communication_preferences_user_id'), 'communication_preferences', ['user_id'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.Enum('BROADCAST', 'DIRECT', 'ANNOUNCEMENT', name='messagetype'), nullable=False),
    sa.Column('target_role', sa.Enum('PARENT', 'TEACHER', 'ALL', name='targetrole'), nullable=True),
    sa.Column('target_class_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_is_deleted'), 'messages', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_messages_message_type'), 'messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_sent_at'), 'messages', ['sent_at'], unique=False)
    op.create_table('message_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'READ', 'FAILED', name='deliverystatus'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel_app', sa.Boolean(), nullable=True),
    sa.Column('channel_sms', sa.Boolean(), nullable=True),
    sa.Column('channel_email', sa.Boolean(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_deliveries_id'), 'message_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_message_deliveries_message_id'), 'message_deliveries', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_deliveries_recipient_id'), 'message_deliveries', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_message_deliveries_status'), 'message_deliveries', ['status'], unique=False)
    # ### end Alembic commands ###

    # Note: Other table drops commented out to preserve existing data
    # If you need to clean up old tables, do it manually


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop communication tables only
    op.drop_index(op.f('ix_message_deliveries_status'), table_name='message_deliveries')
    op.drop_index(op.f('ix_message_deliveries_recipient_id'), table_name='message_deliveries')
    op.drop_index(op.f('ix_message_deliveries_message_id'), table_name='message_deliveries')
    op.drop_index(op.f('ix_message_deliveries_id'), table_name='message_deliveries')
    op.drop_table('message_deliveries')
    op.drop_index(op.f('ix_messages_sent_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_deleted'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_communication_preferences_user_id'), table_name='communication_preferences')
    op.drop_index(op.f('ix_communication_preferences_id'), table_name='communication_preferences')
    op.drop_table('communication_preferences')
    # ### end Alembic commands ###
