"""
Seed all 162 application form fields
Complete implementation with all categories including documents
"""
from sqlalchemy.orm import Session
from ..models.form_configuration import FormFieldMaster


def seed_all_form_fields(db: Session):
    """Seed all 162 form fields across 9 categories (student_info, parent_info, address, academic, additional, financial, sibling, documents, consent)"""

    # Check if fields already exist
    existing = db.query(FormFieldMaster).count()
    if existing > 50:
        print(f"[INFO] Form fields already seeded ({existing} fields). Clearing and reseeding all fields...")
        # Need to clear template fields first due to foreign key
        from ..models.form_configuration import FormTemplateField, SchoolFormConfiguration
        db.query(FormTemplateField).delete()
        db.query(SchoolFormConfiguration).delete()
        db.query(FormFieldMaster).delete()
        db.commit()

    # Clear existing fields for fresh seed (if <50)
    if existing > 0 and existing <= 50:
        from ..models.form_configuration import FormTemplateField, SchoolFormConfiguration
        db.query(FormTemplateField).delete()
        db.query(SchoolFormConfiguration).delete()
        db.query(FormFieldMaster).delete()
        db.commit()

    fields = []

    # ============= STUDENT INFORMATION (Step 1) =============
    # Basic Details
    fields.extend([
        {
            "field_code": "student_first_name",
            "field_label": "First Name",
            "field_type": "text",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": True,
            "validation_rules": {"min_length": 2, "max_length": 50},
            "placeholder": "Enter student's first name",
            "help_text": "As per birth certificate",
        },
        {
            "field_code": "student_middle_name",
            "field_label": "Middle Name",
            "field_type": "text",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": False,
            "validation_rules": {"max_length": 50},
            "placeholder": "Enter middle name (if applicable)",
        },
        {
            "field_code": "student_last_name",
            "field_label": "Last Name",
            "field_type": "text",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": True,
            "validation_rules": {"min_length": 2, "max_length": 50},
            "placeholder": "Enter student's last name",
        },
        {
            "field_code": "student_dob",
            "field_label": "Date of Birth",
            "field_type": "date",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": True,
            "help_text": "As per birth certificate",
        },
        {
            "field_code": "student_gender",
            "field_label": "Gender",
            "field_type": "dropdown",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": True,
            "options": ["Male", "Female", "Other"],
        },
        {
            "field_code": "student_blood_group",
            "field_label": "Blood Group",
            "field_type": "dropdown",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": False,
            "options": ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-", "Unknown"],
        },
        {
            "field_code": "student_place_of_birth",
            "field_label": "Place of Birth",
            "field_type": "text",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": False,
            "placeholder": "City/Town of birth",
        },
        {
            "field_code": "student_nationality",
            "field_label": "Nationality",
            "field_type": "dropdown",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": True,
            "options": ["Indian", "Other"],
        },
        {
            "field_code": "student_religion",
            "field_label": "Religion",
            "field_type": "dropdown",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": False,
            "options": ["Hindu", "Muslim", "Christian", "Sikh", "Buddhist", "Jain", "Other", "Prefer not to say"],
        },
        {
            "field_code": "student_caste_category",
            "field_label": "Caste/Category",
            "field_type": "dropdown",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": False,
            "options": ["General", "SC", "ST", "OBC", "EWS"],
        },
        {
            "field_code": "student_mother_tongue",
            "field_label": "Mother Tongue",
            "field_type": "text",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": False,
            "placeholder": "Primary language spoken at home",
        },

        # Identification
        {
            "field_code": "student_aadhar_number",
            "field_label": "Aadhar Card Number",
            "field_type": "text",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": False,
            "validation_rules": {"pattern": "^[0-9]{12}$"},
            "placeholder": "12-digit Aadhar number",
        },
        {
            "field_code": "student_birth_certificate_number",
            "field_label": "Birth Certificate Number",
            "field_type": "text",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": False,
            "placeholder": "Birth certificate registration number",
        },
        {
            "field_code": "student_passport_number",
            "field_label": "Passport Number",
            "field_type": "text",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": False,
            "placeholder": "Passport number (if applicable)",
            "help_text": "Required only for international students",
        },
        {
            "field_code": "student_identification_number",
            "field_label": "Student Identification Number",
            "field_type": "text",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": False,
            "placeholder": "ID from previous school",
            "help_text": "Student ID or roll number from previous school",
        },

        # Physical Details
        {
            "field_code": "student_height",
            "field_label": "Height (cm)",
            "field_type": "number",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": False,
            "placeholder": "Height in centimeters",
        },
        {
            "field_code": "student_weight",
            "field_label": "Weight (kg)",
            "field_type": "number",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": False,
            "placeholder": "Weight in kilograms",
        },
        {
            "field_code": "student_identification_marks",
            "field_label": "Identification Marks",
            "field_type": "textarea",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": False,
            "placeholder": "Any distinctive physical features",
        },
        {
            "field_code": "student_disabilities",
            "field_label": "Disabilities (if any)",
            "field_type": "textarea",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": False,
            "placeholder": "Describe any physical or learning disabilities",
        },
        {
            "field_code": "student_medical_conditions",
            "field_label": "Special Medical Conditions",
            "field_type": "textarea",
            "category": "student_info",
            "default_step": 1,
            "is_required_by_default": False,
            "placeholder": "Chronic illness, allergies, etc.",
        },
    ])

    # ============= PARENT/GUARDIAN INFORMATION (Step 2) =============
    # Father's Details
    fields.extend([
        {
            "field_code": "father_full_name",
            "field_label": "Father's Full Name",
            "field_type": "text",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": True,
            "validation_rules": {"min_length": 3, "max_length": 100},
        },
        {
            "field_code": "father_dob",
            "field_label": "Father's Date of Birth",
            "field_type": "date",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
        },
        {
            "field_code": "father_education",
            "field_label": "Father's Educational Qualification",
            "field_type": "dropdown",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": True,
            "options": ["Below 10th", "10th Pass", "12th Pass", "Graduate", "Post-Graduate", "Doctorate", "Other"],
        },
        {
            "field_code": "father_occupation",
            "field_label": "Father's Occupation",
            "field_type": "text",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": True,
            "placeholder": "e.g., Engineer, Doctor, Business",
        },
        {
            "field_code": "father_designation",
            "field_label": "Father's Designation",
            "field_type": "text",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
            "placeholder": "Job title/position",
        },
        {
            "field_code": "father_organization",
            "field_label": "Father's Organization/Company",
            "field_type": "text",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
            "placeholder": "Company or organization name",
        },
        {
            "field_code": "father_office_address",
            "field_label": "Father's Office Address",
            "field_type": "textarea",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
        },
        {
            "field_code": "father_office_phone",
            "field_label": "Father's Office Phone",
            "field_type": "phone",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
            "validation_rules": {"pattern": "^[0-9+\\-() ]{10,15}$"},
        },
        {
            "field_code": "father_mobile",
            "field_label": "Father's Mobile Number",
            "field_type": "phone",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": True,
            "validation_rules": {"pattern": "^[0-9]{10}$"},
            "placeholder": "10-digit mobile number",
        },
        {
            "field_code": "father_email",
            "field_label": "Father's Email Address",
            "field_type": "email",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": True,
            "placeholder": "father@example.com",
        },
        {
            "field_code": "father_annual_income",
            "field_label": "Father's Annual Income",
            "field_type": "number",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": True,
            "placeholder": "Annual income in INR",
        },
        {
            "field_code": "father_aadhar",
            "field_label": "Father's Aadhar Number",
            "field_type": "text",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
            "validation_rules": {"pattern": "^[0-9]{12}$"},
        },
        {
            "field_code": "father_pan",
            "field_label": "Father's PAN Number",
            "field_type": "text",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
            "validation_rules": {"pattern": "^[A-Z]{5}[0-9]{4}[A-Z]{1}$"},
            "placeholder": "ABCDE1234F",
        },
        {
            "field_code": "father_photo",
            "field_label": "Father's Photo",
            "field_type": "file",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
            "file_config": {"max_size_mb": 2, "allowed_types": ["image/jpeg", "image/png", "image/jpg"]},
            "help_text": "Upload recent passport size photo",
        },

        # Mother's Details
        {
            "field_code": "mother_full_name",
            "field_label": "Mother's Full Name",
            "field_type": "text",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": True,
            "validation_rules": {"min_length": 3, "max_length": 100},
        },
        {
            "field_code": "mother_dob",
            "field_label": "Mother's Date of Birth",
            "field_type": "date",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
        },
        {
            "field_code": "mother_education",
            "field_label": "Mother's Educational Qualification",
            "field_type": "dropdown",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": True,
            "options": ["Below 10th", "10th Pass", "12th Pass", "Graduate", "Post-Graduate", "Doctorate", "Other"],
        },
        {
            "field_code": "mother_occupation",
            "field_label": "Mother's Occupation",
            "field_type": "text",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": True,
            "placeholder": "e.g., Teacher, Homemaker, Business",
        },
        {
            "field_code": "mother_designation",
            "field_label": "Mother's Designation",
            "field_type": "text",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
        },
        {
            "field_code": "mother_organization",
            "field_label": "Mother's Organization/Company",
            "field_type": "text",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
        },
        {
            "field_code": "mother_office_address",
            "field_label": "Mother's Office Address",
            "field_type": "textarea",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
        },
        {
            "field_code": "mother_office_phone",
            "field_label": "Mother's Office Phone",
            "field_type": "phone",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
        },
        {
            "field_code": "mother_mobile",
            "field_label": "Mother's Mobile Number",
            "field_type": "phone",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": True,
            "validation_rules": {"pattern": "^[0-9]{10}$"},
        },
        {
            "field_code": "mother_email",
            "field_label": "Mother's Email Address",
            "field_type": "email",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": True,
        },
        {
            "field_code": "mother_annual_income",
            "field_label": "Mother's Annual Income",
            "field_type": "number",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
        },
        {
            "field_code": "mother_aadhar",
            "field_label": "Mother's Aadhar Number",
            "field_type": "text",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
            "validation_rules": {"pattern": "^[0-9]{12}$"},
        },
        {
            "field_code": "mother_pan",
            "field_label": "Mother's PAN Number",
            "field_type": "text",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
            "validation_rules": {"pattern": "^[A-Z]{5}[0-9]{4}[A-Z]{1}$"},
            "placeholder": "ABCDE1234F",
        },
        {
            "field_code": "mother_photo",
            "field_label": "Mother's Photo",
            "field_type": "file",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
            "file_config": {"max_size_mb": 2, "allowed_types": ["image/jpeg", "image/png", "image/jpg"]},
            "help_text": "Upload recent passport size photo",
        },

        # Guardian Details
        {
            "field_code": "guardian_full_name",
            "field_label": "Guardian's Full Name",
            "field_type": "text",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
            "help_text": "Only if parents are not available",
        },
        {
            "field_code": "guardian_relationship",
            "field_label": "Relationship with Student",
            "field_type": "text",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
            "placeholder": "e.g., Uncle, Aunt, Grandfather",
        },
        {
            "field_code": "guardian_dob",
            "field_label": "Guardian's Date of Birth",
            "field_type": "date",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
        },
        {
            "field_code": "guardian_occupation",
            "field_label": "Guardian's Occupation",
            "field_type": "text",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
            "placeholder": "Guardian's profession",
        },
        {
            "field_code": "guardian_contact",
            "field_label": "Guardian's Contact Number",
            "field_type": "phone",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
        },
        {
            "field_code": "guardian_email",
            "field_label": "Guardian's Email",
            "field_type": "email",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
        },
        {
            "field_code": "guardian_address",
            "field_label": "Guardian's Address",
            "field_type": "textarea",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
            "placeholder": "Guardian's complete address",
        },
        {
            "field_code": "guardian_aadhar",
            "field_label": "Guardian's Aadhar Number",
            "field_type": "text",
            "category": "parent_info",
            "default_step": 2,
            "is_required_by_default": False,
            "validation_rules": {"pattern": "^[0-9]{12}$"},
            "placeholder": "12-digit Aadhar number",
        },
    ])

    # ============= ADDRESS INFORMATION (Step 3) =============
    fields.extend([
        # Residential Address
        {
            "field_code": "res_house_number",
            "field_label": "House/Flat Number",
            "field_type": "text",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": True,
        },
        {
            "field_code": "res_building_name",
            "field_label": "Building/Apartment Name",
            "field_type": "text",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": False,
        },
        {
            "field_code": "res_street_locality",
            "field_label": "Street/Locality",
            "field_type": "text",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": True,
        },
        {
            "field_code": "res_landmark",
            "field_label": "Landmark",
            "field_type": "text",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": False,
            "placeholder": "Nearby landmark for easy location",
        },
        {
            "field_code": "res_city",
            "field_label": "City/Town",
            "field_type": "text",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": True,
        },
        {
            "field_code": "res_district",
            "field_label": "District",
            "field_type": "text",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": True,
        },
        {
            "field_code": "res_state",
            "field_label": "State",
            "field_type": "text",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": True,
        },
        {
            "field_code": "res_pincode",
            "field_label": "PIN Code",
            "field_type": "text",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": True,
            "validation_rules": {"pattern": "^[0-9]{6}$"},
            "placeholder": "6-digit PIN code",
        },
        {
            "field_code": "res_country",
            "field_label": "Country",
            "field_type": "text",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": True,
        },
        {
            "field_code": "res_residence_type",
            "field_label": "Residence Type",
            "field_type": "dropdown",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": False,
            "options": ["Own House", "Rented", "Leased", "Company Provided", "Other"],
        },
        {
            "field_code": "res_years_at_address",
            "field_label": "Years at Current Address",
            "field_type": "number",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": False,
            "placeholder": "Number of years residing at current address",
        },

        # Permanent Address
        {
            "field_code": "perm_same_as_residential",
            "field_label": "Permanent Address same as Residential",
            "field_type": "checkbox",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": False,
        },
        {
            "field_code": "perm_house_number",
            "field_label": "Permanent House/Flat Number",
            "field_type": "text",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": False,
        },
        {
            "field_code": "perm_building_name",
            "field_label": "Permanent Building/Apartment Name",
            "field_type": "text",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": False,
        },
        {
            "field_code": "perm_street_locality",
            "field_label": "Permanent Street/Locality",
            "field_type": "text",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": False,
        },
        {
            "field_code": "perm_landmark",
            "field_label": "Permanent Address Landmark",
            "field_type": "text",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": False,
            "placeholder": "Nearby landmark for permanent address",
        },
        {
            "field_code": "perm_city",
            "field_label": "Permanent City",
            "field_type": "text",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": False,
        },
        {
            "field_code": "perm_district",
            "field_label": "Permanent District",
            "field_type": "text",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": False,
        },
        {
            "field_code": "perm_state",
            "field_label": "Permanent State",
            "field_type": "text",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": False,
        },
        {
            "field_code": "perm_pincode",
            "field_label": "Permanent PIN Code",
            "field_type": "text",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": False,
        },
        {
            "field_code": "perm_country",
            "field_label": "Permanent Country",
            "field_type": "text",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": False,
        },

        # Communication
        {
            "field_code": "preferred_contact_number",
            "field_label": "Preferred Contact Number",
            "field_type": "phone",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": False,
            "help_text": "Primary number for school communication",
        },
        {
            "field_code": "preferred_email",
            "field_label": "Preferred Email for Communication",
            "field_type": "email",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": False,
            "help_text": "Primary email for school communication",
        },
        {
            "field_code": "whatsapp_number",
            "field_label": "WhatsApp Number",
            "field_type": "phone",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": False,
        },
        {
            "field_code": "emergency_contact_name",
            "field_label": "Emergency Contact Name",
            "field_type": "text",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": True,
        },
        {
            "field_code": "emergency_contact_number",
            "field_label": "Emergency Contact Number",
            "field_type": "phone",
            "category": "address",
            "default_step": 3,
            "is_required_by_default": True,
        },
    ])

    # ============= ACADEMIC INFORMATION (Step 4) =============
    fields.extend([
        # Current Academic
        {
            "field_code": "applying_for_class",
            "field_label": "Applying for Class",
            "field_type": "dropdown",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": True,
            "options": ["Pre-KG", "LKG", "UKG", "Class 1", "Class 2", "Class 3", "Class 4", "Class 5", "Class 6", "Class 7", "Class 8", "Class 9", "Class 10", "Class 11", "Class 12"],
        },
        {
            "field_code": "applying_for_academic_year",
            "field_label": "Academic Year",
            "field_type": "text",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": True,
            "placeholder": "e.g., 2024-25",
        },
        {
            "field_code": "stream_preference",
            "field_label": "Stream/Group Preference",
            "field_type": "dropdown",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
            "options": ["Science", "Commerce", "Arts"],
            "help_text": "For Class 11/12 only",
        },
        {
            "field_code": "second_language",
            "field_label": "Second Language Preference",
            "field_type": "dropdown",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
            "options": ["Hindi", "Sanskrit", "French", "German", "Spanish"],
        },
        {
            "field_code": "third_language",
            "field_label": "Third Language Preference",
            "field_type": "dropdown",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
            "options": ["Hindi", "Sanskrit", "French", "German", "Spanish", "None"],
            "help_text": "If applicable",
        },

        # Previous School
        {
            "field_code": "previous_school_name",
            "field_label": "Previous School Name",
            "field_type": "text",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
        },
        {
            "field_code": "previous_school_address",
            "field_label": "Previous School Address",
            "field_type": "textarea",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
        },
        {
            "field_code": "previous_school_board",
            "field_label": "Previous School Board",
            "field_type": "dropdown",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
            "options": ["CBSE", "ICSE", "State Board", "IB", "IGCSE", "Other"],
        },
        {
            "field_code": "last_class_attended",
            "field_label": "Last Class Attended",
            "field_type": "text",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
        },
        {
            "field_code": "year_of_leaving",
            "field_label": "Year of Leaving Previous School",
            "field_type": "text",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
            "placeholder": "e.g., 2024",
        },
        {
            "field_code": "reason_for_leaving",
            "field_label": "Reason for Leaving Previous School",
            "field_type": "textarea",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
            "placeholder": "Brief reason for changing schools",
        },
        {
            "field_code": "previous_school_contact",
            "field_label": "Previous School Contact Number",
            "field_type": "phone",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
        },
        {
            "field_code": "tc_number",
            "field_label": "Transfer Certificate Number",
            "field_type": "text",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
        },
        {
            "field_code": "last_year_percentage",
            "field_label": "Last Year Percentage/Grade",
            "field_type": "text",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
            "placeholder": "e.g., 85% or A+",
        },
        {
            "field_code": "last_year_division_rank",
            "field_label": "Last Year Division/Rank",
            "field_type": "text",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
            "placeholder": "e.g., First Division, Rank 5",
        },
        {
            "field_code": "best_subject",
            "field_label": "Best Subject",
            "field_type": "text",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
            "placeholder": "Subject student excels in",
        },
        {
            "field_code": "academic_achievements",
            "field_label": "Academic Achievements",
            "field_type": "textarea",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
            "placeholder": "Any awards, medals, or recognitions",
        },
        {
            "field_code": "participation_competitions",
            "field_label": "Participation in Competitions",
            "field_type": "textarea",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
            "placeholder": "Academic competitions, olympiads, etc.",
        },
        {
            "field_code": "awards_recognitions",
            "field_label": "Awards & Recognitions",
            "field_type": "textarea",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
            "placeholder": "Any certificates, awards, or special recognitions",
        },

        # Siblings in same school (Note: These will also be in sibling category)
        {
            "field_code": "sibling_name",
            "field_label": "Sibling's Name (in this school)",
            "field_type": "text",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
        },
        {
            "field_code": "sibling_class",
            "field_label": "Sibling's Current Class",
            "field_type": "text",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
        },
        {
            "field_code": "sibling_section",
            "field_label": "Sibling's Section",
            "field_type": "text",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
            "placeholder": "e.g., A, B, C",
        },
        {
            "field_code": "sibling_admission_number",
            "field_label": "Sibling's Admission Number",
            "field_type": "text",
            "category": "academic",
            "default_step": 4,
            "is_required_by_default": False,
        },

        # Additional Info - Transportation
        {
            "field_code": "transport_required",
            "field_label": "School Transport Required",
            "field_type": "dropdown",
            "category": "additional",
            "default_step": 4,
            "is_required_by_default": False,
            "options": ["Yes", "No"],
        },
        {
            "field_code": "transport_mode",
            "field_label": "Mode of Transportation",
            "field_type": "dropdown",
            "category": "additional",
            "default_step": 4,
            "is_required_by_default": False,
            "options": ["School Bus", "Own Vehicle", "Carpool", "Public Transport", "Walking"],
        },
        {
            "field_code": "bus_route",
            "field_label": "Preferred Bus Route/Stop",
            "field_type": "text",
            "category": "additional",
            "default_step": 4,
            "is_required_by_default": False,
        },
        {
            "field_code": "distance_from_school",
            "field_label": "Distance from School (km)",
            "field_type": "number",
            "category": "additional",
            "default_step": 4,
            "is_required_by_default": False,
        },

        # Health & Medical
        {
            "field_code": "allergies",
            "field_label": "Allergies (Food/Medicine)",
            "field_type": "textarea",
            "category": "additional",
            "default_step": 4,
            "is_required_by_default": False,
            "placeholder": "List any known allergies",
        },
        {
            "field_code": "chronic_illness",
            "field_label": "Chronic Illness",
            "field_type": "textarea",
            "category": "additional",
            "default_step": 4,
            "is_required_by_default": False,
        },
        {
            "field_code": "current_medications",
            "field_label": "Current Medications",
            "field_type": "textarea",
            "category": "additional",
            "default_step": 4,
            "is_required_by_default": False,
        },
        {
            "field_code": "vaccination_status",
            "field_label": "Vaccination Status",
            "field_type": "dropdown",
            "category": "additional",
            "default_step": 4,
            "is_required_by_default": False,
            "options": ["Fully Vaccinated", "Partially Vaccinated", "Not Vaccinated"],
        },
        {
            "field_code": "doctor_contact",
            "field_label": "Doctor's Contact Number",
            "field_type": "phone",
            "category": "additional",
            "default_step": 4,
            "is_required_by_default": False,
            "help_text": "Family doctor or pediatrician contact",
        },

        # Special Requirements
        {
            "field_code": "learning_disabilities",
            "field_label": "Learning Disabilities",
            "field_type": "textarea",
            "category": "additional",
            "default_step": 4,
            "is_required_by_default": False,
            "placeholder": "Dyslexia, ADHD, etc.",
        },
        {
            "field_code": "special_educational_needs",
            "field_label": "Special Educational Needs (SEN)",
            "field_type": "textarea",
            "category": "additional",
            "default_step": 4,
            "is_required_by_default": False,
        },
        {
            "field_code": "behavioral_issues",
            "field_label": "Behavioral Issues",
            "field_type": "textarea",
            "category": "additional",
            "default_step": 4,
            "is_required_by_default": False,
            "placeholder": "Any behavioral concerns school should be aware of",
        },
        {
            "field_code": "language_support_required",
            "field_label": "Language Support Required",
            "field_type": "dropdown",
            "category": "additional",
            "default_step": 4,
            "is_required_by_default": False,
            "options": ["Yes", "No"],
            "help_text": "If student needs ESL or additional language support",
        },
        {
            "field_code": "dietary_restrictions",
            "field_label": "Dietary Restrictions",
            "field_type": "dropdown",
            "category": "additional",
            "default_step": 4,
            "is_required_by_default": False,
            "options": ["Vegetarian", "Non-Vegetarian", "Vegan", "No Restrictions"],
        },

        # Co-curricular
        {
            "field_code": "sports_interest",
            "field_label": "Sports Interest",
            "field_type": "text",
            "category": "additional",
            "default_step": 4,
            "is_required_by_default": False,
            "placeholder": "Cricket, Football, Swimming, etc.",
        },
        {
            "field_code": "arts_music_interest",
            "field_label": "Arts/Music Interest",
            "field_type": "text",
            "category": "additional",
            "default_step": 4,
            "is_required_by_default": False,
        },
        {
            "field_code": "dance_interest",
            "field_label": "Dance Interest",
            "field_type": "text",
            "category": "additional",
            "default_step": 4,
            "is_required_by_default": False,
            "placeholder": "Classical, Contemporary, etc.",
        },
        {
            "field_code": "hobbies",
            "field_label": "Hobbies",
            "field_type": "textarea",
            "category": "additional",
            "default_step": 4,
            "is_required_by_default": False,
        },
        {
            "field_code": "special_talents",
            "field_label": "Special Talents",
            "field_type": "textarea",
            "category": "additional",
            "default_step": 4,
            "is_required_by_default": False,
            "placeholder": "Any unique skills or talents",
        },

        # Financial
        {
            "field_code": "fee_concession_required",
            "field_label": "Fee Concession Required",
            "field_type": "dropdown",
            "category": "financial",
            "default_step": 4,
            "is_required_by_default": False,
            "options": ["Yes", "No"],
        },
        {
            "field_code": "scholarship_request",
            "field_label": "Scholarship Request",
            "field_type": "dropdown",
            "category": "financial",
            "default_step": 4,
            "is_required_by_default": False,
            "options": ["Yes", "No"],
        },
        {
            "field_code": "category_for_concession",
            "field_label": "Category for Fee Concession",
            "field_type": "dropdown",
            "category": "financial",
            "default_step": 4,
            "is_required_by_default": False,
            "options": ["SC/ST", "OBC", "BPL", "EWS", "Other"],
        },
        {
            "field_code": "annual_family_income",
            "field_label": "Annual Family Income",
            "field_type": "number",
            "category": "financial",
            "default_step": 4,
            "is_required_by_default": False,
            "placeholder": "Total family income in INR",
        },
        {
            "field_code": "income_certificate_number",
            "field_label": "Income Certificate Number",
            "field_type": "text",
            "category": "financial",
            "default_step": 4,
            "is_required_by_default": False,
            "placeholder": "Government issued income certificate number",
            "help_text": "Required for EWS/BPL category",
        },
        {
            "field_code": "fee_payment_mode_preference",
            "field_label": "Fee Payment Mode Preference",
            "field_type": "dropdown",
            "category": "financial",
            "default_step": 4,
            "is_required_by_default": False,
            "options": ["Cash", "Cheque", "Online Transfer", "UPI", "Card Payment", "Auto-Debit"],
        },
    ])

    # ============= SIBLING INFORMATION (Step 4 - Additional) =============
    # Note: sibling_name, sibling_class, sibling_section, sibling_admission_number are in academic category
    # This category covers the YES/NO question and OTHER siblings not in this school
    fields.extend([
        {
            "field_code": "has_sibling_in_school",
            "field_label": "Does student have sibling in this school?",
            "field_type": "dropdown",
            "category": "sibling",
            "default_step": 4,
            "is_required_by_default": False,
            "options": ["Yes", "No"],
        },
        {
            "field_code": "sibling_in_school_name",
            "field_label": "Sibling's Name (in this school)",
            "field_type": "text",
            "category": "sibling",
            "default_step": 4,
            "is_required_by_default": False,
            "help_text": "Sibling already studying in this school",
        },
        {
            "field_code": "sibling_in_school_class",
            "field_label": "Sibling's Current Class (in this school)",
            "field_type": "text",
            "category": "sibling",
            "default_step": 4,
            "is_required_by_default": False,
        },
        {
            "field_code": "sibling_in_school_section",
            "field_label": "Sibling's Section (in this school)",
            "field_type": "text",
            "category": "sibling",
            "default_step": 4,
            "is_required_by_default": False,
        },
        {
            "field_code": "other_sibling_name",
            "field_label": "Other Sibling's Name",
            "field_type": "text",
            "category": "sibling",
            "default_step": 4,
            "is_required_by_default": False,
            "help_text": "Siblings not in this school",
        },
        {
            "field_code": "other_sibling_age",
            "field_label": "Other Sibling's Age",
            "field_type": "number",
            "category": "sibling",
            "default_step": 4,
            "is_required_by_default": False,
        },
        {
            "field_code": "other_sibling_school",
            "field_label": "Other Sibling's School Name",
            "field_type": "text",
            "category": "sibling",
            "default_step": 4,
            "is_required_by_default": False,
        },
        {
            "field_code": "other_sibling_class",
            "field_label": "Other Sibling's Class/Course",
            "field_type": "text",
            "category": "sibling",
            "default_step": 4,
            "is_required_by_default": False,
        },
    ])

    # ============= DOCUMENTS (Step 5) =============
    # Document upload fields for comprehensive documentation
    fields.extend([
        {
            "field_code": "doc_birth_certificate",
            "field_label": "Birth Certificate",
            "field_type": "file",
            "category": "documents",
            "default_step": 5,
            "is_required_by_default": True,
            "file_config": {"max_size_mb": 5, "allowed_types": ["application/pdf", "image/jpeg", "image/png", "image/jpg"]},
        },
        {
            "field_code": "doc_student_photo",
            "field_label": "Student Passport Size Photo",
            "field_type": "file",
            "category": "documents",
            "default_step": 5,
            "is_required_by_default": True,
            "file_config": {"max_size_mb": 2, "allowed_types": ["image/jpeg", "image/png", "image/jpg"]},
        },
        {
            "field_code": "doc_address_proof",
            "field_label": "Address Proof",
            "field_type": "file",
            "category": "documents",
            "default_step": 5,
            "is_required_by_default": True,
            "file_config": {"max_size_mb": 5, "allowed_types": ["application/pdf", "image/jpeg", "image/png", "image/jpg"]},
            "help_text": "Utility bill, rent agreement, or Aadhar card",
        },
        {
            "field_code": "doc_parent_id_proof",
            "field_label": "Parent ID Proof (Aadhar)",
            "field_type": "file",
            "category": "documents",
            "default_step": 5,
            "is_required_by_default": True,
            "file_config": {"max_size_mb": 5, "allowed_types": ["application/pdf", "image/jpeg", "image/png", "image/jpg"]},
        },
        {
            "field_code": "doc_transfer_certificate",
            "field_label": "Transfer Certificate / School Leaving Certificate",
            "field_type": "file",
            "category": "documents",
            "default_step": 5,
            "is_required_by_default": False,
            "file_config": {"max_size_mb": 5, "allowed_types": ["application/pdf", "image/jpeg", "image/png", "image/jpg"]},
            "help_text": "From previous school (if applicable)",
        },
        {
            "field_code": "doc_marksheet",
            "field_label": "Previous Year Mark Sheet / Report Card",
            "field_type": "file",
            "category": "documents",
            "default_step": 5,
            "is_required_by_default": False,
            "file_config": {"max_size_mb": 5, "allowed_types": ["application/pdf", "image/jpeg", "image/png", "image/jpg"]},
        },
        {
            "field_code": "doc_character_certificate",
            "field_label": "Character Certificate",
            "field_type": "file",
            "category": "documents",
            "default_step": 5,
            "is_required_by_default": False,
            "file_config": {"max_size_mb": 5, "allowed_types": ["application/pdf", "image/jpeg", "image/png", "image/jpg"]},
        },
        {
            "field_code": "doc_migration_certificate",
            "field_label": "Migration Certificate",
            "field_type": "file",
            "category": "documents",
            "default_step": 5,
            "is_required_by_default": False,
            "file_config": {"max_size_mb": 5, "allowed_types": ["application/pdf", "image/jpeg", "image/png", "image/jpg"]},
            "help_text": "Required if changing education boards",
        },
        {
            "field_code": "doc_caste_certificate",
            "field_label": "Caste Certificate",
            "field_type": "file",
            "category": "documents",
            "default_step": 5,
            "is_required_by_default": False,
            "file_config": {"max_size_mb": 5, "allowed_types": ["application/pdf", "image/jpeg", "image/png", "image/jpg"]},
            "help_text": "For SC/ST/OBC category",
        },
        {
            "field_code": "doc_income_certificate",
            "field_label": "Income Certificate",
            "field_type": "file",
            "category": "documents",
            "default_step": 5,
            "is_required_by_default": False,
            "file_config": {"max_size_mb": 5, "allowed_types": ["application/pdf", "image/jpeg", "image/png", "image/jpg"]},
            "help_text": "For EWS/BPL fee concession",
        },
        {
            "field_code": "doc_disability_certificate",
            "field_label": "Disability Certificate",
            "field_type": "file",
            "category": "documents",
            "default_step": 5,
            "is_required_by_default": False,
            "file_config": {"max_size_mb": 5, "allowed_types": ["application/pdf", "image/jpeg", "image/png", "image/jpg"]},
            "help_text": "If applicable",
        },
        {
            "field_code": "doc_ews_certificate",
            "field_label": "EWS (Economically Weaker Section) Certificate",
            "field_type": "file",
            "category": "documents",
            "default_step": 5,
            "is_required_by_default": False,
            "file_config": {"max_size_mb": 5, "allowed_types": ["application/pdf", "image/jpeg", "image/png", "image/jpg"]},
        },
        {
            "field_code": "doc_sports_certificate",
            "field_label": "Sports Achievement Certificates",
            "field_type": "file",
            "category": "documents",
            "default_step": 5,
            "is_required_by_default": False,
            "file_config": {"max_size_mb": 10, "allowed_types": ["application/pdf", "image/jpeg", "image/png", "image/jpg"]},
            "help_text": "For sports quota admission",
        },
        {
            "field_code": "doc_medical_certificate",
            "field_label": "Medical Certificate",
            "field_type": "file",
            "category": "documents",
            "default_step": 5,
            "is_required_by_default": False,
            "file_config": {"max_size_mb": 5, "allowed_types": ["application/pdf", "image/jpeg", "image/png", "image/jpg"]},
        },
        {
            "field_code": "doc_vaccination_records",
            "field_label": "Vaccination Records / Immunization Card",
            "field_type": "file",
            "category": "documents",
            "default_step": 5,
            "is_required_by_default": False,
            "file_config": {"max_size_mb": 5, "allowed_types": ["application/pdf", "image/jpeg", "image/png", "image/jpg"]},
        },
        {
            "field_code": "doc_noc",
            "field_label": "No Objection Certificate (NOC)",
            "field_type": "file",
            "category": "documents",
            "default_step": 5,
            "is_required_by_default": False,
            "file_config": {"max_size_mb": 5, "allowed_types": ["application/pdf", "image/jpeg", "image/png", "image/jpg"]},
            "help_text": "If applicable",
        },
        {
            "field_code": "doc_affidavit",
            "field_label": "Affidavit",
            "field_type": "file",
            "category": "documents",
            "default_step": 5,
            "is_required_by_default": False,
            "file_config": {"max_size_mb": 5, "allowed_types": ["application/pdf", "image/jpeg", "image/png", "image/jpg"]},
            "help_text": "If required by school",
        },
        {
            "field_code": "doc_other",
            "field_label": "Other Document",
            "field_type": "file",
            "category": "documents",
            "default_step": 5,
            "is_required_by_default": False,
            "file_config": {"max_size_mb": 10, "allowed_types": ["application/pdf", "image/jpeg", "image/png", "image/jpg"]},
            "help_text": "Any additional document",
        },
    ])

    # ============= CONSENT & DECLARATION (Step 5) =============
    # Consent checkboxes
    fields.extend([
        {
            "field_code": "consent_true_information",
            "field_label": "I declare that all information provided is true",
            "field_type": "checkbox",
            "category": "consent",
            "default_step": 5,
            "is_required_by_default": True,
        },
        {
            "field_code": "consent_school_rules",
            "field_label": "I agree to abide by school rules and regulations",
            "field_type": "checkbox",
            "category": "consent",
            "default_step": 5,
            "is_required_by_default": True,
        },
        {
            "field_code": "consent_photo_video",
            "field_label": "I consent to photo/video usage for school activities",
            "field_type": "checkbox",
            "category": "consent",
            "default_step": 5,
            "is_required_by_default": False,
        },
        {
            "field_code": "consent_medical_emergency",
            "field_label": "I consent to medical emergency treatment if required",
            "field_type": "checkbox",
            "category": "consent",
            "default_step": 5,
            "is_required_by_default": True,
        },
        {
            "field_code": "consent_data_privacy",
            "field_label": "I consent to data privacy policy and usage",
            "field_type": "checkbox",
            "category": "consent",
            "default_step": 5,
            "is_required_by_default": True,
        },
        {
            "field_code": "terms_conditions_acceptance",
            "field_label": "I accept all terms and conditions",
            "field_type": "checkbox",
            "category": "consent",
            "default_step": 5,
            "is_required_by_default": True,
        },
    ])

    # Insert all fields
    for field_data in fields:
        field = FormFieldMaster(**field_data)
        db.add(field)

    db.commit()

    print(f"[SUCCESS] Seeded {len(fields)} form fields!")
    print(f"  - Student Info: {sum(1 for f in fields if f['category'] == 'student_info')}")
    print(f"  - Parent Info: {sum(1 for f in fields if f['category'] == 'parent_info')}")
    print(f"  - Address: {sum(1 for f in fields if f['category'] == 'address')}")
    print(f"  - Academic: {sum(1 for f in fields if f['category'] == 'academic')}")
    print(f"  - Additional: {sum(1 for f in fields if f['category'] == 'additional')}")
    print(f"  - Financial: {sum(1 for f in fields if f['category'] == 'financial')}")
    print(f"  - Sibling: {sum(1 for f in fields if f['category'] == 'sibling')}")
    print(f"  - Documents: {sum(1 for f in fields if f['category'] == 'documents')}")
    print(f"  - Consent: {sum(1 for f in fields if f['category'] == 'consent')}")


if __name__ == "__main__":
    from sqlalchemy import create_engine
    from sqlalchemy.orm import sessionmaker

    engine = create_engine('sqlite:///./admission.db')
    Session = sessionmaker(bind=engine)
    db = Session()

    try:
        seed_all_form_fields(db)
    finally:
        db.close()
